[package]
name = "rango"
version = "0.1.0"
edition = "2021"
 
authors = ["Marie Martinot De Salles DERANDRAINY"]
description = "A powerful, Django-like async web framework built on top of Axum and Tokio."
homepage = "https://github.com/Dera2Salles/Rango"
repository = "https://github.com/Dera2Salles/Rango"
license = "MIT"

[features]
default = ["templates"]
templates = ["minijinja"]
db = ["sqlx"]
auth = ["tower-sessions"]

[dependencies]
rango_macros = { path = "../macros" }

axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "cors", "trace"] }

minijinja = { version = "2.0", features = ["loader"], optional = true }

sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "postgres",
    "any",
    "migrate",
    "macros"
], optional = true }

tower-sessions = { version = "0.12", optional = true }
