[package]
name = "rango_macros"
version = "0.1.1"
edition = "2021"

authors = ["Marie Martinot De Salles DERANDRAINY"]
description = "Procedural macros for the Rango web framework."
repository = "https://github.com/Dera2Salles/Rango"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
